version: "3"

services:
  quasar:
    tty: true # docker run -t
    restart: unless-stopped
    image: quasar
    command: /bin/sh -c "yarn && quasar dev"
    ports:
    - '8080:8080'
    volumes:
      - "./app:/app"
      - "./app/node_modules:/app/node_modules"